name: wstan_dart
version: 0.0.1
description: Wstan server implemented in Dart.
author: kari <master@readeasy.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  crypto: '>=2.0.1 <3.0.0'
  pointycastle: '0.10.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
